<?php

/**
 * @file
 * The module file for UNL System.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function unl_system_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
    /** @var \Drupal\Core\Config\ConfigFactoryInterface */
    $config_factory = \Drupal::service('config.factory');
    $config = $config_factory->get('unl_system.settings');

    $form['site_information']['#weight'] = -10;

    $form['unl_affiliation'] = [
      '#type' => 'details',
      '#title' => 'UNL Affiliation',
      '#open' => TRUE,
      '#weight' => -9,
    ];
    $form['unl_affiliation']['affiliation_name'] = [
      '#type' => 'textfield',
      '#title' => t('Affiliation Name'),
      '#default_value' => $config->get('affiliation_name'),
    ];
    $form['unl_affiliation']['affiliation_url'] = [
      '#type' => 'url',
      '#title' => t('Affiliation URL'),
      '#default_value' => $config->get('affiliation_url'),
    ];
    $form['#validate'][] = '_unl_system_system_site_information_settings_validate';
    $form['#submit'][] = '_unl_system_system_site_information_settings_submit';
  }

  // If Content Moderation is enabled, add every new content type to the
  // editorial workflow. (The content_moderation modules takes care of
  // removal upon deletion.)
  $moduleHandler = \Drupal::service('module_handler');
  if ($moduleHandler->moduleExists('content_moderation')) {
    if ($form_id == 'node_type_add_form') {
      $form['actions']['save_continue']['#submit'][] = '_unl_system_node_type_add_form_submit';
    }
  }
}

/**
 * Validates system_site_information_settings form.
 *
 * @param array $form
 *   A array describing the form.
 * @param Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 */
function _unl_system_system_site_information_settings_validate(array $form, FormStateInterface $form_state) {
  $values = $form_state->getValues();

  if ($values['affiliation_name'] && empty($values['affiliation_url'])) {
    $form_state->setErrorByName('affiliation_url', 'Affiliation URL is required if Affiliation Name is defined.');
  }
  if (empty($values['affiliation_name']) && $values['affiliation_url']) {
    $form_state->setErrorByName('affiliation_name', 'Affiliation Name is required if Affiliation URL is defined.');
  }
}

/**
 * Submits system_site_information_settings form.
 *
 * @param array $form
 *   A array describing the form.
 * @param Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 */
function _unl_system_system_site_information_settings_submit(array $form, FormStateInterface $form_state) {
  $values = $form_state->getValues();

  /** @var \Drupal\Core\Config\ConfigFactoryInterface */
  $config_factory = \Drupal::service('config.factory');

  /** @var \Drupal\Core\Config\Config */
  $config = $config_factory->getEditable('unl_system.settings');
  $config->set('affiliation_name', $values['affiliation_name']);
  $config->set('affiliation_url', $values['affiliation_url']);
  $config->save();
}

/**
 * Submits node_type_add_form form.
 *
 * @param array $form
 *   A array describing the form.
 * @param Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 */
function _unl_system_node_type_add_form_submit(array $form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  $workflow = \Drupal::entityTypeManager()->getStorage('workflow')->loadByProperties(['id' => 'editorial'])['editorial'];
  $config = $workflow->getTypePlugin()->getConfiguration();
  $config['entity_types']['node'][] = $values['type'];
  $workflow->getTypePlugin()->setConfiguration($config);
  $workflow->save();
}

/**
 * Implements hook_preprocess_block().
 */
function unl_system_preprocess_block(&$vars) {
  if ($vars['plugin_id'] == 'system_branding_block') {
    $config_factory = \Drupal::service('config.factory');
    $config = $config_factory->get('unl_system.settings');

    $vars['affiliation_name'] = $config->get('affiliation_name');
    $vars['affiliation_url'] = $config->get('affiliation_url');
  }
}

/**
 * Implements hook_local_tasks_alter().
 */
function unl_system_menu_local_tasks_alter(&$data, $route_name) {

  $logged_in = \Drupal::currentUser()->isAuthenticated();
  if ($logged_in) {
    //Remove Delete menu item from the menu local task
    unset($data['tabs'][0]['entity.node.delete_form']);
    // Rearrange the local tasks tabs so that Delete is at the end.
    $data['tabs'][0]['entity.node.book_outline_form']['#weight'] = 100;
    // $data['tabs'][0]['entity.node.delete_form']['#weight'] = 110;
    $data['tabs'][0]['entity.taxonomy_term.delete_form']['#weight'] = 110;
    // Change the "Latest version" tab title provided by Content Moderation.
    $data['tabs'][0]['content_moderation.workflows:node.latest_version_tab']['#link']['title'] = 'Latest draft';
  }
}

