name: 'UNL Configuration'
description: 'Modifies configuration UI for UNL sites'
package: UNL

type: module
core_version_requirement: ^8 || ^9 || ^10

version: 1.x

dependencies:
  - drupal:config_ignore
