<?php

/**
 * Implements hook_entity_type_build().
 */
function unl_contenthub_entity_type_build(array &$entity_types) {
  if (isset($entity_types['node'])) {
    $entity_types['node']->setHandlerClass('access', 'Drupal\unl_contenthub\ContentHubNodeAccessControlHandler');
  }
}

/**
 * Implements hook_local_tasks_alter().
 */
function unl_contenthub_local_tasks_alter(&$local_tasks) {
  $local_tasks['entity_share_client.admin_content_page']['title'] = t('Content Hub');
  $local_tasks['entity_share_client.admin_content_pull_form']['title'] = t('Pull from Content Hub');
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function unl_contenthub_menu_links_discovered_alter(&$links) {
  $links['entity_share_client.admin_content_page']['title'] = t('Content Hub');
  $links['entity_share_client.admin_content_pull_form']['title'] = t('Pull from Content Hub');
}

/**
 * Implements hook_preprocess_html().
 */
function unl_contenthub_preprocess_html(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name === 'entity_share_client.admin_content_page' ||
    $route_name === 'entity_share_client.admin_content_pull_form') {
    $variables['head_title']['title'] = t('Pull from Content Hub');
  }
}

/**
 * Implements hook_preprocess_page_title().
 */
function unl_contenthub_preprocess_page_title(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name === 'entity_share_client.admin_content_page' ||
    $route_name === 'entity_share_client.admin_content_pull_form') {
    $variables['title'] = t('Pull from Content Hub');
  }
}
