<?php

/**
 * Implements hook_block_info()
 */
function unl_multisite_block_info() {
  $blocks = array();

  $blocks['my_sites'] = array(
    'info' => 'My Sites',
    'cache' => DRUPAL_CACHE_PER_USER,
  );

  return $blocks;
}

/**
 * Implements hook_block_view()
 */
function unl_multisite_block_view($delta = '') {
  switch ($delta) {
    case 'my_sites':
      return unl_multisite_block_view_my_sites();
      break;
    default:
      return array();
  }
}

/**
 * Implements hook_block_view('my_sites').
 * Displays the list of sites/roles for the current user.
 */
function unl_multisite_block_view_my_sites() {
  if (\Drupal::currentUser()->isAnonymous()) {
    return array();
  }

  require_once 'unl_site_creation.php';

  $block = array();
  $block['content'] = _unl_get_user_audit_content(\Drupal::currentUser()->name);

  return $block;
}

/**
 * Implements hook_help().
 */
function unl_multisite_help($path, $arg) {
  switch ($path) {
    case 'admin/sites/unl/aliases':
    case 'admin/sites/unl/%/aliases':
      return '<p>Be careful when deleting aliases. While long, ugly paths may not appear to be needed they may still be in use -  for instance in a ProxyPass setup on another server.</p>';
  }
}

/**
 * Implementation of hook_permission().
 */
function unl_multisite_permission() {
  return array(
    'unl site creation' => array(
      'title' => t('Site Creation'),
      'description' => t('Create new Drupal sites using the UNL profile.'),
      'restrict access' => TRUE,
     ),
  );
}

/**
 * Implements hook_element_info_alter().
 */
function unl_multisite_element_info_alter(array &$types) {
  // Attach our extra CSS for toolbar icons.
  if (isset($types['toolbar'])) {
    $types['toolbar']['#attached']['library'][] = 'unl_multisite/toolbar';
  }
}

/**
 * Implementation of hook_theme().
 */
//function unl_multisite_theme() {
//  return array(
//    'unl_site_details' => array(
//      'variables' => array('site_path' => NULL, 'uri' => NULL, 'db_prefix' => NULL),
//      'file' => 'unl_site_creation.php',
//    ),
//    'unl_table' => array(
//      'render element' => 'form',
//      'file' => 'unl_site_creation.php',
//    ),
//  );
//}
