<?php

use Drupal\user\Entity\Role;

/**
 * Implements hook_install_tasks().
 *
 * hook_install() can't be used in a profile when installing from existing
 * config, so this technique is used.
 * https://www.drupal.org/project/drupal/issues/2982052#comment-13044759
 *
 * Here we set a flag to identify we are doing a site install so that
 * we can sidestep the RELEASE SAVEPOINT ProxySQL issue detailed here:
 * https://github.com/unlcms/project-herbie/issues/366
 */
function herbie_install_tasks(&$install_state) {
  // Referenced in patched version of core/modules/mysql/src/Driver/Database/mysql/Connection.php.
  \Drupal::state()->set('is_herbie_install', TRUE);
  return [];
}

/**
 * Uninstall Chosen module.
 */
function herbie_update_8101(&$sandbox) {
  drupal_flush_all_caches();
  $srvc = \Drupal::service('herbie.module_remove');
  $srvc->remove('chosen');
  $srvc->remove('chosen_field');
  $srvc->remove('chosen_lib');
}

/**
 * Delete n_major_areas_emphasis field.
 */
function herbie_update_8102(&$sandbox) {
  $field = \Drupal\field\Entity\FieldConfig::loadByName('node', 'major', 'n_major_areas_emphasis');
  if (!empty($field)) {
    $field->delete();
  }
  $field_storage = \Drupal\field\Entity\FieldStorageConfig::loadByName('node', 'n_major_areas_emphasis');
  if (!empty($field_storage)) {
    $field_storage->delete();
  }
  $field = \Drupal\field\Entity\FieldConfig::loadByName('node', 'major', 'n_major_minors');
  if (!empty($field)) {
    $field->delete();
  }
  $field_storage = \Drupal\field\Entity\FieldStorageConfig::loadByName('node', 'n_major_minors');
  if (!empty($field_storage)) {
    $field_storage->delete();
  }
}

/**
 * Update wysiwyg format on p_b_accrd_item_body.
 */
function herbie_update_8103(&$sandbox) {
  $paragraphs = \Drupal::entityTypeManager()
    ->getStorage('paragraph')
    ->loadByProperties([
      'type' => 'accordion_item',
    ]);

  foreach ($paragraphs as $paragraph) {
    $paragraph->p_b_accrd_item_body->format = 'standard';
    $paragraph->save();
  }
}

/**
 * Update wysiwyg format on p_b_tab_item_body.
 */
function herbie_update_8104(&$sandbox) {
  $paragraphs = \Drupal::entityTypeManager()
    ->getStorage('paragraph')
    ->loadByProperties([
      'type' => 'tab_item',
    ]);

  foreach ($paragraphs as $paragraph) {
    $paragraph->p_b_tab_item_body->format = 'standard';
    $paragraph->save();
  }
}

/**
 * Update max_length of m_rv_html_representation field to 1000 characters.
 */
function herbie_update_8105(&$sandbox) {
  // Resize the Columns.
  $database = \Drupal::database();
  $database->query("ALTER TABLE media__m_rv_html_representation MODIFY m_rv_html_representation_value VARCHAR(1000)");
  $database->query("ALTER TABLE media_revision__m_rv_html_representation MODIFY m_rv_html_representation_value 	VARCHAR(1000)");

  // Update Storage Schema.
  $storage_key = 'media.field_schema_data.m_rv_html_representation';
  $storage_schema = \Drupal::keyValue('entity.storage_schema.sql');
  $field_schema = $storage_schema->get($storage_key);
  $field_schema['media__m_rv_html_representation']['fields']['m_rv_html_representation']['length'] = 1000;
  $field_schema['media_revision__m_rv_html_representation']['fields']['m_rv_html_representation']['length'] = 1000;
  $storage_schema->set($storage_key, $field_schema);

  // Update field configuration.
  $config = \Drupal::configFactory()
    ->getEditable('field.storage.media.m_rv_html_representation');
  $config->set('settings.max_length', 1000);
  $config->save(TRUE);
}

/**
 * Update WYSIWYG format for the Body field (n_person_bio) in the Person content type. From Simple to Standard.
 */
function herbie_update_8106(&$sandbox) {
  $storage = \Drupal::entityTypeManager()->getStorage('node');
  // Load nodes of type 'person'
  $nodes = $storage->loadByProperties(['type' => 'person']);

  foreach ($nodes as $node) {
    if ($node->hasField('n_person_bio')) {
      $node->get('n_person_bio')->format = 'standard';
      $node->save();
    }
  }
}


/**
 * Update the authenticated role if it has a specific permission.
 */
function herbie_update_8107(&$sandbox) {
  $role_name = 'authenticated';
  $permission = 'edit any person content';
  $role = Role::load(id: $role_name);

  if ($role && $role->hasPermission($permission)) {
    $role->revokePermission($permission);
    $role->save();
  }
}

/**
 * Update/migrate widgets from using select2 to tagify for custom content types created by developers.
 */
function herbie_update_8108(&$sandbox) {
  if (\Drupal::service('module_handler')->moduleExists('tagify')) {

    $storage = \Drupal::entityTypeManager()->getStorage('entity_form_display');
    $display_ids = $storage->getQuery()->execute();

    foreach ($storage->loadMultiple($display_ids) as $form_display) {
      $components = $form_display->getComponents();

      foreach ($components as $field_name => $component) {
        if (!empty($component['type']) && $component['type'] === 'select2_entity_reference') {

          $field_definitions = \Drupal::service('entity_field.manager')
            ->getFieldDefinitions(
              $form_display->getTargetEntityTypeId(),
              $form_display->getTargetBundle()
            );

          $field_definition = $field_definitions[$field_name];

          if (isset($field_definitions[$field_name])) {
            if ($field_name === 'uid') {
              $plugin_id = 'entity_reference_autocomplete';
            } else {
              $plugin_id = 'tagify_entity_reference_autocomplete_widget';
            }

            $widget_manager = \Drupal::service('plugin.manager.field.widget');

            $plugin = $widget_manager->createInstance($plugin_id, [
              'field_definition' => $field_definition,
              'settings' => [],
              'third_party_settings' => [],
            ]);

            $default_settings = $plugin->getSettings();

            if ($plugin_id === 'tagify_entity_reference_autocomplete_widget') {
              $default_settings['parent_selection'] = 0;
            }

            $form_display->setComponent($field_name, [
              'type' => $plugin_id,
              'settings' => $default_settings,
            ] + $component);

            $form_display->save();
          }
        }
      }
    }
  }
}
