<?php

/**
 * @file
 * The .module file for Twig UI Templates.
 */

/**
 * Implements hook_theme().
 */
function twig_ui_theme($existing, $type, $theme, $path) {
  // hook_theme() functions are unaware of the theme for which a registry is
  // being built. \Drupal\twig_ui\Registry::build() sets a global variable,
  // which contains this information and is retrieved below.
  global $_twig_ui_registry_theme;
  // If the global variable hasn't been set, then don't return templates yet.
  // \Drupal\twig_ui\Registry::build() will call twig_ui_theme() a second time.
  if ($_twig_ui_registry_theme) {
    $twig_ui_path = \Drupal::service('twig_ui.template_manager')->getDirectoryPathByTheme($_twig_ui_registry_theme, FALSE);

    return drupal_find_theme_templates($existing, '.html.twig', $twig_ui_path);
  }

  return [];
}
