field.value.css:
  type: mapping
  label: Default value
  mapping:
    value:
      type: text
      label: CSS

field.widget.settings.css:
  type: mapping
  label: CSS widget settings
  mapping:
    toolbar:
      type: boolean
      label: Toolbar enabled
    buttons:
      type: sequence
      label: Buttons
      sequence:
        type: string
        label: Button

field.formatter.settings.css:
  type: mapping
  label: CSS formatter settings
  mapping:
    location:
      type: string
      label: Location
    prefix:
      type: string
      label: Selector Prefix
    fixed_prefix_value:
      type: string
      label: Fixed Prefix Value
