<?php

use Drupal\user\UserInterface;

/**
 * Implements hook_install().
 */
function unl_user_install() {
  \Drupal::configFactory()->getEditable('user.settings')
    ->set('register', UserInterface::REGISTER_ADMINISTRATORS_ONLY)
    ->save(TRUE);
}

/**
 * Implements hook_user_login().
 */
function unl_user_user_login(\Drupal\Core\Session\AccountInterface $account) {
  // Schedule a user data update for the account.
  /** @var \Drupal\Core\Queue\QueueFactory $queue_factory */
  $queue_factory = \Drupal::service('queue');
  /** @var \Drupal\Core\Queue\QueueInterface $queue */
  $queue = $queue_factory->get('cron_unl_user_update_user_data', true);
  $item = new \stdClass();
  $item->uid = $account->id();
  $queue->createItem($item);
}
