bundle: herbie
required:
  - unl_five.settings
  - unl_five_herbie.settings
  - entity_usage.settings
  - moderated_content_bulk_publish.settings
  - theme_per_user.settings
  - views.view.content
  - views.view.taxonomy_term
  - system.action.draft_current
  - system.action.pin
  - system.action.publish_latest
  - system.action.unpin
  - system.action.unpublish_current
  - linkit.linkit_profile.content_linkit_profile
