unl_news.settings:
  type: config_object
  label: 'UNL News settings'
  mapping:
    tag_ids:
      type: sequence
      label: 'Tags'
      sequence:
        type: integer
        label: 'Tag'
    ianrnews_tag_ids:
      type: sequence
      label: 'IANR News Tags'
      sequence:
        type: integer
        label: 'IANR News Tag'
