<?php

/**
 * @file
 * Primary module hooks for Codemirror editor test module.
 */

/**
 * Implements hook_codemirror_editor_assets_alter().
 */
function codemirror_editor_test_codemirror_editor_assets_alter(array &$assets) {
  $assets['js'][] = 'mode/clike/clike.js';
  $assets['js'][] = 'mode/php/php.js';
  // The minified files should also be registered.
  $assets['js'][] = 'mode/css/css.min.js';
}

/**
 * Implements hook_codemirror_mode_info_alter().
 */
function codemirror_editor_test_codemirror_mode_info_alter(array &$modes) {
  $modes['php']['usage'][] = 'codemirror_editor_test';
}
