<?php

/**
 * @file
 * This module extends Group functionality.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_complete_form_alter().
 */
function unl_group_field_widget_complete_form_alter(&$field_widget_complete_form, FormStateInterface $form_state, $context) {
  // Hide the Group selector field on the node edit page if no groups exist.
  if ($context['widget']->getPluginId() == 'entitygroupfield_select_widget') {
    $groups = \Drupal::entityTypeManager()->getStorage('group')->loadMultiple();
    if (!$groups) {
      $field_widget_complete_form['widget']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_field_widget_single_element_form_alter().
 */
function unl_group_field_widget_single_element_form_alter(&$field_widget_complete_form, FormStateInterface $form_state, $context) {
  // Hide the alias/path field for the Group Relationship. This principally is on
  // the node edit form. We're not concerned with the relationship entity at all.
  if ($context['widget']->getPluginId() == 'entitygroupfield_select_widget') {
    $field_widget_complete_form['subform']['#access'] = FALSE;
  }
}

/**
 * Implements hook_update_1001().
 * Some group pages have created "Contact Info" blocks without descriptions because the description
 * field was disabled during their creation.
 * This update ensures a description is added to prevent a
 * PHP deprecated function warning: Deprecated function: strnatcasecmp().
 */
function unl_group_update_1001() {
  if (\Drupal::service('module_handler')->moduleExists('group')) {
    $group_storage = \Drupal::entityTypeManager()->getStorage('group');

    if ($group_storage) {
      $group_ids = $group_storage->getQuery()
        ->condition('type', 'group_subsite')
        ->accessCheck(TRUE)
        ->execute();

      if ($group_ids) {
        // Load the block storage service.
        $custom_blocks = \Drupal::entityTypeManager()->getStorage('block_content');
        // Load all custom block entities.
        $blocks = $custom_blocks->loadMultiple();

        // Loop through all blocks.
        foreach ($blocks as $block) {
          $block_id = $block->id();
          $block_type = $block->bundle();

          if (!empty($block_id) && $block_type == 'contact_info') {
            // If contact info block's description is empty set the description
            if (!$block->get('info')->getValue()) {
              $contact_info_block_description = 'Contact us';
              $block->set('info', $contact_info_block_description);
              $block->save();
              \Drupal::logger('unl_group')->notice('Updated description for block ID: @id', ['@id' => $block_id]);
            }
          }
        }
      }

      // Return a status message.
      return t('Contact Info block descriptions have been updated.');
    }
  }
}
