<?php

/**
 * @file
 * This module extends Group functionality.
 */

use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_block_build_alter().
 */
function unl_group_block_build_alter(array &$build, BlockPluginInterface $block) {
  if ($block->getPluginId() === 'group_content_menu:gcm_subsite_menu') {
    // Prevent BigPipe from making this block lazy.
    if (isset($build['#lazy_builder'])) {
      unset($build['#lazy_builder']);
    }

    // Disable placeholder creation so it renders in initial HTML.
    $build['#create_placeholder'] = FALSE;
  }
}

/**
 * Implements hook_field_widget_complete_form_alter().
 */
function unl_group_field_widget_complete_form_alter(&$field_widget_complete_form, FormStateInterface $form_state, $context) {
  // Hide the Group selector field on the node edit page if no groups exist.
  if ($context['widget']->getPluginId() == 'entitygroupfield_select_widget') {
    $groups = \Drupal::entityTypeManager()->getStorage('group')->loadMultiple();
    if (!$groups) {
      $field_widget_complete_form['widget']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_field_widget_single_element_form_alter().
 */
function unl_group_field_widget_single_element_form_alter(&$field_widget_complete_form, FormStateInterface $form_state, $context) {
  // Hide the alias/path field for the Group Relationship. This principally is on
  // the node edit form. We're not concerned with the relationship entity at all.
  if ($context['widget']->getPluginId() == 'entitygroupfield_select_widget') {
    $field_widget_complete_form['subform']['#access'] = FALSE;
  }
}
